sudo: required

language: generic
services:
  - docker
    
before_install:
  - docker build -t kennichi/docker-react -f Dockerfile.dev .
    
script:
  - docker run -e CI=true kennichi/docker-react npm run test